index_page = {
    'el': {
        'instagram_profile': 'Προφίλ Instagram (Πρέπει να είναι δημόσιο)',
        'create_game': 'Δημιουργία παιχνιδιού',
        'options': 'Επιλογές',
        'option1': 'επιλογή 1',
        'option2': 'επιλογή 2',
        'option3': 'option3',
        'option4': 'επιλογή 4',
        'option5': 'επιλογή 5',
        'action1': 'πράξη 1',
        'no_ig_name': 'Δεν δόθηκε Instagram',
        'no_following': 'Δεν ακολουθείς κανέναν ή το προφίλ σου είναι ιδιωτικό',
        'no_player_name': 'Δεν έχεις ορίσει όνομα παίχτη',
        'game_not_exists': 'Το παιχνίδι δεν υπάρχει',
        'submit': 'Νεό παιχνίδι',
        'difficulty': 'Δυσκολία',
        'interval': 'Διάλειμμα',
        'scenarios': 'Αριθμός σεναρίων',
        'difficulty_description': 'Όσο μεργαλύτερη η δυσκολία τόσο λιγότερα χρήματα παίρνεις για ακραία σενάρια.',
        'or': 'ή',
        'random_game': 'Τυχαίο παιχνίδι',
        'private': 'Ιδιωτικό παιχνίδι'
    },

    'en': {
        'instagram_profile': 'Instagram profile (Must be public)',
        'create_game': 'Create Game',
        'options': 'Options',
        'option1': 'option1s',
        'option2': 'option2',
        'option3': 'option3',
        'option4': 'option4s (Non-lethal)',
        'option5': 'option5',
        'action1': 'action1',
        'no_ig_name': 'No Instagram given',
        'no_following': "You're not following anyone or your profile is private",
        'no_player_name': "You haven't set your player name",
        'game_not_exists': "The game does not exist",
        'submit': 'New game',
        'difficulty': 'Difficulty',
        'interval': 'Interval',
        'scenarios': 'Scenario count',
        'difficulty_description': "The greater the difficulty, the less the money you get for extreme scenarios.",
        'or': 'or',
        'random_game': 'Random game',
        'private': 'Private game'
    }
}

in_game_page = {
    'el': {
        'would_you': 'Θα',
        'action4': "πράξη 4",
        'action1': "πράξη 1",
        'action3': "πράξη 3",
        'action2': "πράξη 2",
        "relations": [
            "σχέση 1",
            "σχέση 2",
            "σχέση 3",
            "σχέση 4"
        ],
        'with': 'με',
        'option2': 'πιθανότητα να option2',
        'option3': 'πιθανότητα να πάθεις option3',
        'option4': 'πιθανότητα να πάθεις κάποιο option4',
        'if_she_was_your': 'αν ήταν',
        'sou': 'σου',
        'option1': 'αν ήσουν option1',
        'start_game': 'Εκκίνηση παιχνιδιού',
        'yes': 'Ναι',
        'no': 'Όχι',
        'join_game': 'Συμμετοχή στο παιχνίδι',
        'player_name': 'Όνομα παίχτη',
        'continue': 'Συνέχεια',
        'thn': 'τον/την',
        'for': 'για',
        'players': 'Παίκτες',
        'chat': 'Συνομιλία',
        'type_your_message': 'Γράψε το μήνυμά σου'
    },

    'en': {
        'would_you': 'Would you',
        'action4': "action4",
        'action1': "action1",
        'action3': "action3",
        'action2': "action2",
        "relations": [
            "second cousin",
            "cousin",
            "sister",
            "mother"
        ],
        'with': 'with',
        'option2': 'chance of option2',
        'option3': 'chance of you getting option3',
        'option4': 'chance of you getting a non-lethal option4',
        'if_she_was_your': 'if she was your',
        'sou': '',
        'option1': 'if you were in a option1',
        'start_game': 'Start Game',
        'yes': 'Yes',
        'no': 'No',
        'join_game': 'Join Game',
        'player_name': 'Player name',
        'continue': 'Continue',
        'thn': '',
        'for': 'for',
        'players': 'Players',
        'chat': 'Chat',
        'type_your_message': 'Type your message'
    }
}